apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: monitor-task-github-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: pullrequesturl
    value: $(body.pull_request.html_url)
  - name: statusesurl
    value: $(body.pull_request.statuses_url)

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: monitor-task-gitlab-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: pullrequesturl
    value: $(body.object_attributes.url)
  - name: statusesurl
    value: projects/$(body.project.id)/statuses/$(body.object_attributes.last_commit.id)